server {
    listen 80;

    # 1. Phục vụ giao diện React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Điều hướng API sang Product Service (Cổng 8001)
    location /api/products {
        proxy_pass http://product-service:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Điều hướng API sang Order Service (Cổng 8002)
    location /api/orders {
        proxy_pass http://order-service:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Điều hướng API sang Payment Service (Cổng 8003)
    location /api/payments {
        proxy_pass http://payment-service:8003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}